### ISSUE TITLE
Can not delete .log files

### ISSUE THREAD

**Issue by nlc-gene** [JetBrains/ideolog#15] opened 2017-09-20 02:06 UTC
I am using PyCharm. With your plugin enabled I can not right click on .log files and delete them. PyCharm complains that the file is read only. With the plugin disabled I can delete the .log files. The plugin also stops me from adding notes to log files I have open.

I am using ideolog v172.0.3.0 under PyCharm 2017.2.3 on Linux.

**Comment by mfilippov** [comment] 2017-09-20 07:53
@knah Is it fixed in 0.4.0?

**Comment by knah** [comment] 2017-09-20 08:12
Yes, it was fixed in 0.4.0.
As for being unable to edit .log files - this was intended. The plugin was initially created for files of large sizes (1MB+). As such, we rely on the fact that the file isn't edited, only appended. This includes making the user unable to edit the file.
We could think about some kind of note-adding feature, but you might want to create a separate issue for that.

**Closed by knah** 2017-09-20 08:12 UTC
